version: "3"
services:
  redis:
    image: redis:alpine
    container_name: ms-redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  #   rabbitmq:
  #     image: rabbitmq:management-alpine
  #     container_name: ms-rabbitmq
  #     ports:
  #       - 5672:5672
  #       - 15672:15672

  cache:
    build: ./cache
    env_file: .env
    container_name: ms-cache
    image: node:16-alpine
    working_dir: /code
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./cache/:/code
    depends_on:
      - redis
    #  - rabbitmq

  rest:
    build: ./rest
    env_file: .env
    container_name: ms-rest
    image: node:16-alpine
    working_dir: /code
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./rest/:/code
    depends_on:
      - redis
    #  - rabbitmq

  gateway:
    build: ./gateway
    env_file: .env
    container_name: ms-gateway
    image: node:16-alpine
    working_dir: /code
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./gateway/:/code
    depends_on:
      - cache
      - redis
    #  - rabbitmq